export const LOADING_STATE = 'LOADING_STATE';
export const AUTH_DATA = 'AUTH_DATA';
export const EMAIL_VERIFY_LOADING_STATE = 'EMAIL_VERIFY_LOADING_STATE';
export const RESEND_EMAIL_VERIFY_LOADING_STATE = 'RESEND_EMAIL_VERIFY_LOADING_STATE';
export const WORK_PROFILE_LOADING_STATE = 'WORK_PROFILE_LOADING_STATE';