export const LOADING_STATE = 'LOADING_STATE';
export const CLOCK_IN = 'CLOCK_IN';
export const GET_TIMEIN_TIMEOUT = 'GET_TIMEIN_TIMEOUT';
export const TIMEIN_TIMEOUT_LOADING_STATE = 'TIMEIN_TIMEOUT_LOADING_STATE';
export const GET_WEEKLY_TIMEIN_TIMEOUT = 'GET_WEEKLY_TIMEIN_TIMEOUT';
export const WEEKLY_TIMEIN_TIMEOUT_LOADING_STATE = 'WEEKLY_TIMEIN_TIMEOUT_LOADING_STATE';
export const TAKE_BREAK_LOADING_STATE = 'TAKE_BREAK_LOADING_STATE';