export const LOADING_STATE = 'LOADING_STATE';
export const CLOCK_IN = 'CLOCK_IN';
export const GET_TIMEIN_TIMEOUT = 'GET_TIMEIN_TIMEOUT';
export const TIMEIN_TIMEOUT_LOADING_STATE = 'TIMEIN_TIMEOUT_LOADING_STATE';
export const GET_WEEKLY_TIMEIN_TIMEOUT = 'GET_WEEKLY_TIMEIN_TIMEOUT';
export const WEEKLY_TIMEIN_TIMEOUT_LOADING_STATE = 'WEEKLY_TIMEIN_TIMEOUT_LOADING_STATE';
export const TAKE_BREAK_LOADING_STATE = 'TAKE_BREAK_LOADING_STATE';
export const GET_EMPLOYEE_PERSONAL_LOADING_STATE = 'GET_EMPLOYEE_PERSONAL_LOADING_STATE';
export const GET_EMPLOYEE_PERSONAL_DATA = 'GET_EMPLOYEE_PERSONAL_DATA';
export const IS_UPDATED_EMPLOYEE_PERSONAL_DATA = 'IS_UPDATED_EMPLOYEE_PERSONAL_DATA';
export const GET_ALL_TASK = 'GET_ALL_TASK';
export const GET_ALL_TASK_LOADING_STATE = 'GET_ALL_TASK_LOADING_STATE';
export const GET_SINGLE_TASK = 'GET_SINGLE_TASK';
export const GET_SINGLE_TASK_LOADING_STATE = 'GET_SINGLE_TASK_LOADING_STATE';

export const GET_DAYLY_AGENDA_LOADING_STATE = 'GET_DAYLY_AGENDA_LOADING_STATE';
export const GET_DAYLY_AGENDA_DATA = 'GET_DAYLY_AGENDA_DATA';

export const GET_WEEKLY_AGENDA_LOADING_STATE = 'GET_WEEKLY_AGENDA_LOADING_STATE';
export const GET_WEEKLY_AGENDA_DATA = 'GET_WEEKLY_AGENDA_DATA';

export const GET_MONTHLY_AGENDA_LOADING_STATE = 'GET_MONTHLY_AGENDA_LOADING_STATE';
export const GET_MONTHLY_AGENDA_DATA = 'GET_MONTHLY_AGENDA_DATA';

export const GET_YEARLY_AGENDA_LOADING_STATE = 'GET_YEARLY_AGENDA_LOADING_STATE';
export const GET_YEARLY_AGENDA_DATA = 'GET_YEARLY_AGENDA_DATA';

export const CLOCK_OUT_LOADING_STATE = 'CLOCK_OUT_LOADING_STATE';
export const CLOCK_OUT_DATA = 'CLOCK_OUT_DATA';