export const LOADING_STATE = 'LOADING_STATE';
export const CLOCK_IN = 'CLOCK_IN';
export const GET_TIMEIN_TIMEOUT = 'GET_TIMEIN_TIMEOUT';
export const TIMEIN_TIMEOUT_LOADING_STATE = 'TIMEIN_TIMEOUT_LOADING_STATE';